### ISSUE TITLE
.STRINGZ drops spaces after commas

### ISSUE THREAD

**Issue by hawkfalcon** [WChargin/lc3web#1]
Thanks for the awesome web version! I've discovered a small issue reproducible by other people. If you put a , character in a .STRINGZ, the next space is dropped.

EX:
LABEL .STRINGZ "foo, bar"

Gives foo,bar.

**Comment by wchargin** [comment]
You're right, thanks! There are other issues with `.STRINGZ`, like `"do foo; then do bar"` is treated as invalid because I parse comments before string literals (so the string parser sees `"do foo`). This is obviously wrong.

I'm working on a rewrite that's much nicer and has unit tests. I've already fixed these in the new version…
![image](https://cloud.githubusercontent.com/assets/4317806/10702563/53d5ace0-797f-11e5-8dcd-630d8a634b9b.png)
but I realize that that's not very useful to you, so I'll try to update this version soon.

**Comment by hawkfalcon** [comment]
Thanks for the quick response, no hurry!
Edit: Wow, that was quick. I'll try that out. Thanks.

**Comment by wchargin** [comment]
Okay! You can now use the new assembler in the current version of the simulator by going to [git.io/lc3web#asmfix](https://git.io/lc3web#asmfix) (or https://wchargin.github.io/lc3web/#asmfix).

**Please advise me of any bugs** you see in the new assembler. If I don't hear anything, I'll make this the default in one week. If there are still bugs then, I can claim it's supposed to scare people because it's Halloween.

Proof:
![image](https://cloud.githubusercontent.com/assets/4317806/10702950/96ee13d0-7981-11e5-8bf1-3f2afc067023.png)
![image](https://cloud.githubusercontent.com/assets/4317806/10703015/ed47403a-7981-11e5-94ac-5d222de2e832.png)

You should also see much better error messages as a result:
![image](https://cloud.githubusercontent.com/assets/4317806/10702974/b7241776-7981-11e5-86a9-af0a32a90869.png)

**Comment by hawkfalcon** [comment]
My bug was fixed with that:
<img width="459" alt="bplgu4a" src="https://cloud.githubusercontent.com/assets/1509618/10703210/4937ecd6-7983-11e5-9da1-3507291fab00.png">

Note: the new version (as it is fixed, I suppose), uses more memory locations to store the data, so I had to update my pointers to the strings in my data file. 
All other behavior seemed to be the same! (with my one test)

**Comment by wchargin** [comment]
Whoa, when you say "uses more memory locations to store the data," you just mean that the string is longer, as it should be, right? I just want to confirm that it's not using more memory than it _should_.

**Comment by hawkfalcon** [comment]
Sorry, I put that badly. AFAIK it uses the correct amount of spaces NOW. It didn't before (it was missing spaces). Therefore, I had to change locations.

**Comment by wchargin** [comment]
Great, good to hear :smile: sorry for the inconvenience.

I've published the new version in case you're interested, or if you want to look at the [new assembler code](https://github.com/WChargin/lc3/blob/master/src/core/assemble.js) or [test cases](https://github.com/WChargin/lc3/blob/master/test/core/assemble_test.js). I'd encourage you to do so if you're interested! I think it should be reasonably understandable, and I'm happy to answer any questions about it.

(The new version of the assembler [used in this repository](https://github.com/WChargin/lc3web/blob/gh-pages/js/lc3_as.js#L835) is painful to read, because it's the output of a Babel transpilation.)

**Comment by hawkfalcon** [comment]
No, thank _you_. This tool is really amazing, 100x better than the java version and 1000x better than attempting to use wine w/ the windows version. 
I'll take a look, thanks! It looks very well written. Surprised you aren't showing it off on your website.

**Comment by wchargin** [comment]
:heart:

**Comment by hawkfalcon** [comment]
~~Also, I didn't read the readme, and have been posting issues in the wrong place. 
For posterity, the new location is https://github.com/WChargin/lc3. I apologize.~~

> _edit by @wchargin:_ nope, please open issues here!

And as this issue is fixed, I'll close it. That was incredibly fast. Thanks again.

**Comment by wchargin** [comment]
Well, I posted the README after you posted this! :smile:

I'd actually prefer if issues remain here for now. The version at [wchargin/lc3](https://github.com/WChargin/lc3) is _not_ production-ready and doesn't aim to be; posting issues there would be kind of a moot point.

**Comment by wchargin** [comment]
Reopening this so that I remember to merge it in a week.
